# Generated by Django 5.2.7 on 2025-11-07 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField(default=list)),
                ('current_turn', models.CharField(choices=[('B', 'Black'), ('W', 'White')], default='B', max_length=1)),
                ('winner', models.CharField(blank=True, choices=[('B', 'Black'), ('W', 'White')], max_length=1, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='othello_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
