# Generated by Django 5.2.7 on 2025-10-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=4)),
                ('attempts', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('session_id', models.CharField(max_length=40)),
            ],
        ),
    ]
