# Generated by Django 5.2.7 on 2025-11-05 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HitAndBlow', '0002_remove_game_session_id_game_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField()),
                ('number', models.CharField(max_length=4)),
                ('hit', models.IntegerField()),
                ('blow', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HitAndBlow.game')),
            ],
        ),
    ]
